language: python
python:
    # See https://github.com/rgalanakis/hostthedocs/pull/24 for details
    # - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy3"
install:
  - pip install tox-travis
script:
  - tox
